export const site = {
  username: 'somarjez',
  name: 'Jezreel Ramos',
  role: 'Data Analyst & Developer',
  roleSub: 'Data · Web · Project Management · AI',
  location: 'Philippines 🇵🇭',
  // The four areas I'm building my path around (priority order).
  roles: ['Data Analyst', 'Web Developer', 'Project Management', 'AI / Machine Learning'],
  // Headline tools, for the intro's skills line.
  stack: ['Python', 'SQL', 'JavaScript', 'React', 'Java', 'C#'],
  tagline: 'A Computer Science student turning data and ideas into clean, working software.',
  hero:
    'A Computer Science student building toward data analysis, web development, project management, and AI through coursework and team projects.',
  bio: "I'm a Computer Science student and developer in the Philippines, focused on four areas: data analysis, web development, project management, and AI. My work so far is academic: course and team projects in web and machine learning, including Flask and Django platforms, exploratory data analysis in Python, and a hybrid Machine Learning and Knowledge-Representation system for affordable, sustainable housing. I work in Python, SQL, JavaScript and TypeScript, React, Java, and C#, with tools like Jupyter, Power BI, Tableau, and Git. I enjoy turning data and ideas into clean, working software, and I'm looking to grow through real projects and collaboration.",
  education: {
    degree: 'BS Computer Science, major in Information Systems',
    detail: 'Coursework across software engineering, database systems, and machine learning.',
  },
  focus: [
    {
      icon: 'fa-chart-line',
      label: 'Data Analysis',
      blurb: 'Exploratory analysis, visualization, and insight with Python, SQL, Power BI, and Tableau.',
    },
    {
      icon: 'fa-laptop-code',
      label: 'Web Development',
      blurb: 'Full-stack web apps with React, Flask, and Django.',
    },
    {
      icon: 'fa-diagram-project',
      label: 'Project Management',
      blurb: 'Planning, SDLC, version control, testing, and delivery.',
    },
    {
      icon: 'fa-brain',
      label: 'AI / Machine Learning',
      blurb: 'ML models, computer vision, and prompt engineering for coursework and research.',
    },
  ],
  // GitHub orgs to feature explicitly (membership may be private, so they won't
  // appear via the public user-orgs API). Their public repos are shown too.
  featuredOrgs: ['santacruz-bible-christian-church'],
  // Replace with a real Formspree form id; falls back to mailto when empty.
  formspreeId: '',
  links: {
    email: 'jezreelramoz@gmail.com',
    github: 'https://github.com/somarjez',
    linkedin: 'https://www.linkedin.com/in/somarjez',
    facebook: 'https://www.facebook.com/thenthen05',
    website: 'https://somarjez.github.io/',
    // Served from public/resume/. Filename is professional so downloads are ATS-friendly.
    resume: '/resume/Jezreel-Ramos-Resume.pdf',
  },
  skills: [
    {
      icon: 'fa-code',
      title: 'Languages',
      tags: ['Python', 'Dart', 'TypeScript', 'JavaScript', 'C# (.NET)', 'Java'],
    },
    {
      icon: 'fa-palette',
      title: 'Frontend & Mobile',
      tags: ['React / Next.js', 'Flutter', 'Tailwind CSS', 'HTML5 / CSS3', 'Vue.js'],
    },
    {
      icon: 'fa-server',
      title: 'Backend & Data',
      tags: ['Flask', 'Django', 'Firebase / Firestore', 'SQLite', 'MySQL / PostgreSQL', 'SQL', 'REST APIs'],
    },
    {
      icon: 'fa-brain',
      title: 'AI / Machine Learning',
      tags: [
        'Machine Learning',
        'TensorFlow',
        'Scikit-learn',
        'Pandas',
        'Jupyter',
        'NLP',
        'Computer Vision',
        'Knowledge Representation & Reasoning',
        'Prompt Engineering',
        'Data Analysis',
      ],
    },
    {
      icon: 'fa-tools',
      title: 'Tools',
      tags: ['Git / GitHub', 'VS Code', 'Figma', 'Power BI', 'Tableau', 'Excel'],
    },
  ],
  // `url` holds the public "Show credential" verification link; leave empty to hide the verify button.
  // `badge` is the Credly/issuer badge image served from public/credentials/badges/.
  // `certificate` is the PDF or image served from public/credentials/certificates/.
  certifications: [
    // Priority order: Data Science, AI, CodeChum, DICT, others.
    {
      icon: 'fa-chart-line',
      title: 'Introduction to Data Science',
      issuer: 'Cisco Networking Academy',
      issued: 'Aug 20, 2026',
      credentialId: '',
      url: '',
      badge: '/credentials/badges/introduction-to-data-science.png',
      certificate: '/credentials/certificates/introduction-to-data-science.pdf',
      certificatePreview: '/credentials/previews/introduction-to-data-science.webp',
      description:
        'Cisco training covering the data science lifecycle, data types and sources, exploratory analysis, and the roles data plays in decision-making.',
      skills: ['Data Science', 'Data Analysis', 'Exploratory Analysis'],
    },
    {
      icon: 'fa-chart-line',
      title: 'Data Science Essentials with Python',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 16, 2026',
      credentialId: '2c37fc3e-618c-4c25-a2dd-97a73f6b8c25',
      url: 'https://www.credly.com/earner/earned/badge/2c37fc3e-618c-4c25-a2dd-97a73f6b8c25',
      badge: '/credentials/badges/data-science-essentials-with-python.png',
      certificate: '/credentials/certificates/data-science-essentials-with-python.pdf',
      certificatePreview: '/credentials/previews/data-science-essentials-with-python.webp',
      description:
        'Hands-on Python data science covering CSV and DataFrame workflows, evaluation and querying, grouping and left merges, missing-data cleanup, Matplotlib charts, basic linear models, goodness of fit, and hypothesis testing.',
      skills: ['Python', 'Pandas', 'Data Cleaning', 'Matplotlib', 'Linear Models', 'Hypothesis Testing'],
    },
    {
      icon: 'fa-chart-pie',
      title: 'Data Analytics Essentials',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 9, 2026',
      credentialId: '0eaec38c-405a-4c1c-afe5-e977b47fe0d8',
      url: 'https://www.credly.com/earner/earned/badge/0eaec38c-405a-4c1c-afe5-e977b47fe0d8',
      badge: '/credentials/badges/data-analytics-essentials.png',
      certificate: '/credentials/certificates/data-analytics-essentials.pdf',
      certificatePreview: '/credentials/previews/data-analytics-essentials.webp',
      description:
        'Cisco training in the analytics process, data characteristics and acquisition, transformation, preparation, basic statistics, and portfolio-ready work using Excel, SQL, and Tableau.',
      skills: ['Data Analysis', 'Data Preparation', 'Statistics', 'Excel', 'SQL', 'Tableau'],
    },
    {
      icon: 'fa-robot',
      title: 'Introduction to Modern AI',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 18, 2026',
      credentialId: '6e6eb5de-05cf-4cbe-9140-45853f4645d0',
      url: 'https://www.credly.com/earner/earned/badge/6e6eb5de-05cf-4cbe-9140-45853f4645d0',
      badge: '/credentials/badges/introduction-to-modern-ai.png',
      certificate: '/credentials/certificates/introduction-to-modern-ai.pdf',
      certificatePreview: '/credentials/previews/introduction-to-modern-ai.webp',
      description:
        'Cisco training in AI and machine-learning basics, photo classification, object detection and segmentation, machine translation limits, LLM fundamentals, prompting, chatbots, tool use, and multimodal prompting.',
      skills: ['Machine Learning', 'Computer Vision', 'LLM Prompting', 'Chatbots', 'Multimodal AI'],
    },
    {
      icon: 'fa-file-lines',
      title: 'Apply AI: Update Your Resume',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 19, 2026',
      credentialId: 'c219cac6-0de3-4aa2-ba94-57fa6b192047',
      url: 'https://www.credly.com/earner/earned/badge/c219cac6-0de3-4aa2-ba94-57fa6b192047',
      badge: '/credentials/badges/apply-ai-update-your-resume.png',
      certificate: '/credentials/certificates/apply-ai-update-your-resume.pdf',
      certificatePreview: '/credentials/previews/apply-ai-update-your-resume.webp',
      description:
        'A privacy-aware resume workflow using AI to redact sensitive data, extract evidence-based accomplishments, create ATS-friendly skills and bullets, validate results, style a PDF, and tailor it to a target role.',
      skills: ['Generative AI', 'Data Privacy', 'Resume Analysis', 'ATS Optimization', 'Human Validation'],
    },
    {
      icon: 'fa-wand-magic-sparkles',
      title: 'AI-Powered Future: Mastering Prompt Engineering in Generative AI',
      issuer: 'DICT Region V',
      issued: 'Sep 6, 2025',
      credentialId: 'DICTR5:2025-W-MPEG-1',
      controlNumber: '2025-IBWEB1146',
      url: 'https://drive.google.com/file/d/1rzpcezg5hZj9UAAy7o3VKEeauUd7LkqP/view',
      badge: null,
      certificate: '/credentials/certificates/ai-powered-future-prompt-engineering.pdf',
      certificatePreview: '/credentials/previews/ai-powered-future-prompt-engineering.webp',
      description:
        'DICT Region V training focused on prompt engineering and practical use of generative AI.',
      skills: ['Prompt Engineering', 'Generative AI', 'AI Literacy'],
    },
    {
      icon: 'fa-robot',
      title: 'AI-Driven Software Development: From Wireframe to App – with a Focus on Security and Assurance',
      issuer: 'Computer Science Society Organization',
      issued: 'Dec 3, 2025',
      credentialId: '',
      url: '',
      badge: null,
      certificate: '/credentials/certificates/ai-driven-software-development.jpg',
      certificatePreview: '/credentials/previews/ai-driven-software-development.jpg',
      description:
        'Participation at Laguna State Polytechnic University, Santa Cruz Campus, exploring wireframe-to-app development with a focus on security and assurance.',
      skills: ['Software Development', 'Wireframing', 'Application Security', 'Software Assurance'],
    },
    {
      icon: 'fa-gears',
      title: 'Java Software Engineering I',
      issuer: 'CodeChum',
      issued: 'Dec 9, 2025',
      credentialId: '',
      url: 'https://lspu.codechum.com/certificates/18552',
      badge: null,
      certificate: '/credentials/certificates/java-software-engineering-i.pdf',
      certificatePreview: '/credentials/previews/java-software-engineering-i.webp',
      description:
        'CodeChum certification for CMSC 309 Software Engineering 1, A.Y. 2025–2026, BSCS3A, completed with a score of 400/431.',
      skills: ['Java', 'Software Engineering', 'Programming', 'CMSC 309'],
    },
    {
      icon: 'fa-shield-halved',
      title: '4-hour Webinar on Data Privacy Awareness',
      issuer: 'DICT Region XI',
      issued: 'Sep 10, 2025',
      credentialId: '',
      url: 'https://qr.me-qr.com/text/UVt0jYss',
      badge: null,
      certificate: '/credentials/certificates/data-privacy-awareness.pdf',
      certificatePreview: '/credentials/previews/data-privacy-awareness.webp',
      description:
        'Attendance at a four-hour data privacy awareness webinar hosted by the Davao del Sur Provincial Office of DICT Region XI.',
      skills: ['Data Privacy', 'Privacy Awareness', 'Responsible Data Handling'],
    },
    {
      icon: 'fa-lock',
      title: 'Are your s3crets safe? Fortifying Your Arsenal Against AWS Bucket Breaches',
      issuer: 'GC Bitbarkada',
      issued: 'Oct 1, 2025',
      credentialId: '',
      url: '',
      badge: null,
      certificate: '/credentials/certificates/aws-bucket-breaches.pdf',
      certificatePreview: '/credentials/previews/aws-bucket-breaches.webp',
      description:
        'A career-enhancement upskilling course focused on strengthening defenses against AWS bucket breaches.',
      skills: ['AWS Security', 'Bucket Security', 'Cloud Security'],
    },
    {
      icon: 'fa-laptop',
      title: 'Integrated OS – Be More Digi-TALINO',
      issuer: 'Integrated Office Solutions, Inc.',
      issued: 'Sep 5, 2025',
      credentialId: '',
      url: '',
      badge: null,
      certificate: '/credentials/certificates/integrated-os-digi-talino.pdf',
      certificatePreview: '/credentials/previews/integrated-os-digi-talino.webp',
      description:
        'A digital-skills session covering productivity applications, digital communication, smart research, data safety, and security.',
      skills: ['Digital Productivity', 'Digital Communication', 'Smart Research', 'Data Safety'],
    },
    {
      icon: 'fa-code',
      title: 'Hour of Code — AI Ready ASEAN Programme',
      issuer: 'Break the Fake Movement / ASEAN Foundation',
      issued: 'Aug 25, 2025',
      credentialId: '',
      url: '',
      badge: null,
      certificate: '/credentials/certificates/hour-of-code-ai-ready-asean.pdf',
      certificatePreview: '/credentials/previews/hour-of-code-ai-ready-asean.webp',
      description:
        'Three hours of online learning delivered by Break the Fake Movement with the ASEAN Foundation and supported by Google.org and DICT Aurora.',
      skills: ['AI Literacy', 'Digital Skills', 'Online Learning'],
    },
  ],
}
