export const site = {
  username: 'somarjez',
  name: 'Jezreel Ramos',
  role: 'Full-Stack & AI Developer',
  roleSub: 'Web · Mobile · AI · Data Science',
  location: 'Philippines 🇵🇭',
  hero:
    'I build full-stack web, mobile, and AI-driven applications — from Flutter commerce apps to Flask/Django platforms, machine-learning systems, and data-analytics work for real-world problems.',
  bio: "I'm a developer who builds across the stack — web, mobile, and AI. My work spans Flutter mobile commerce, Flask and Django web platforms, and machine-learning projects, including a hybrid ML + Knowledge-Representation system for affordable housing in the Philippines. I also work in data science and analytics — exploratory data analysis, visualization, and prompt engineering for generative AI. I care about clean architecture, thoughtful UX, and shipping work that solves real problems. I'm comfortable across C#/.NET, Java, Python, TypeScript, React/Next.js, and Dart.",
  education: {
    degree: 'BS Computer Science — Information Systems',
    detail: 'Focus on software engineering, database systems, and machine learning.',
  },
  focus: [
    { icon: 'fa-layer-group', label: 'Full-Stack Web' },
    { icon: 'fa-mobile-screen', label: 'Mobile Apps' },
    { icon: 'fa-brain', label: 'AI / Machine Learning' },
  ],
  // Replace with a real Formspree form id; falls back to mailto when empty.
  formspreeId: '',
  links: {
    email: 'jezreelramoz@gmail.com',
    github: 'https://github.com/somarjez',
    linkedin: 'https://linkedin.com/in/jezreel-ramos-49b029350',
    facebook: 'https://www.facebook.com/thenthen05',
    website: 'https://somarjez.github.io/',
  },
  skills: [
    {
      icon: 'fa-code',
      title: 'Languages',
      tags: ['Python', 'Dart', 'TypeScript', 'JavaScript', 'C# (.NET)', 'Java'],
    },
    {
      icon: 'fa-palette',
      title: 'Frontend & Mobile',
      tags: ['React / Next.js', 'Flutter', 'Tailwind CSS', 'HTML5 / CSS3'],
    },
    {
      icon: 'fa-server',
      title: 'Backend & Data',
      tags: ['Flask', 'Django', 'Firebase / Firestore', 'SQLite', 'MySQL / PostgreSQL', 'SQL', 'REST APIs'],
    },
    {
      icon: 'fa-brain',
      title: 'AI / Machine Learning',
      tags: [
        'Machine Learning',
        'TensorFlow',
        'Scikit-learn',
        'Pandas',
        'Jupyter',
        'Computer Vision',
        'Knowledge Representation & Reasoning',
        'Prompt Engineering',
        'Data Analysis',
      ],
    },
    {
      icon: 'fa-tools',
      title: 'Tools',
      tags: ['Git / GitHub', 'VS Code', 'Figma', 'Power BI', 'Tableau', 'Excel'],
    },
  ],
  // `url` holds the public "Show credential" verification link; leave empty to
  // hide the verify button. `credentialId` renders as a mono reference line.
  certifications: [
    {
      icon: 'fa-robot',
      title: 'Introduction to Modern AI',
      issuer: 'Cisco',
      issued: 'Jun 2026',
      credentialId: '6e6eb5de-05cf-4cbe-9140-45853f4645d0',
      url: '',
      skills: ['Machine Learning', 'Computer Vision', 'Chatbots', 'AI Prompting', 'Machine Translation'],
    },
    {
      icon: 'fa-chart-line',
      title: 'Data Science Essentials with Python',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 2026',
      credentialId: '2c37fc3e-618c-4c25-a2dd-97a73f6b8c25',
      url: '',
      skills: ['Exploratory Data Analysis', 'Linear Regression', 'Data Cleaning', 'Data Visualization', 'Storytelling', 'Jupyter'],
    },
    {
      icon: 'fa-wand-magic-sparkles',
      title: 'AI-Powered Future: Mastering Prompt Engineering in Generative AI',
      issuer: 'DICT — Philippines',
      issued: 'Sep 2025',
      credentialId: '',
      url: '',
      skills: ['Artificial Intelligence (AI)', 'Prompt Writing', 'Accurate Prompting', 'Generative AI'],
    },
    {
      icon: 'fa-shield-halved',
      title: 'Data Privacy Awareness',
      issuer: 'DICT — Philippines',
      issued: 'Sep 2025',
      credentialId: '',
      url: '',
      skills: ['Data Privacy', 'Data Privacy Awareness'],
    },
    {
      icon: 'fa-gears',
      title: 'Software Engineering I',
      issuer: 'CodeChum',
      issued: 'Dec 2025',
      credentialId: '',
      url: '',
      skills: ['Java', 'Project Management', 'Programming', 'SDLC', 'Data Structures', 'Version Control', 'Testing', 'Quality Assurance', 'Security'],
    },
    {
      icon: 'fa-chart-pie',
      title: 'Data Analytics Essentials',
      issuer: 'Cisco Networking Academy',
      issued: 'Jun 2026',
      credentialId: '0eaec38c-405a-4c1c-afe5-e977b47fe0d8',
      url: '',
      skills: ['Data Analysis', 'Data Visualization', 'Microsoft Power BI', 'Tableau', 'SQL', 'Microsoft Excel'],
    },
  ],
}
